# Generated by Django 3.2.11 on 2022-05-27 18:50

import uuid

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0003_shopuser_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopuser",
            name="activation_key",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=authapp.models.get_activation_key_expires
            ),
        ),
    ]
